item {
  id: 1
  name: 'n07739125'
}

item {
  id: 2
  name: 'n07753592'
}

item {
  id: 3
  name: 'n07747607'
}

item {
  id: 4
  name: 'n07749582'
}

item {
  id: 5
  name: 'n07753275'
}

item {
  id: 6
  name: 'n07767847'
}